from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.runnables import RunnableParallel


load_dotenv()


# Initialize two different LLMs
model1 = ChatOpenAI()
model2 = ChatGoogleGenerativeAI(model="gemini-2.5-flash")


# Prompt 1:
# Generate short and simple notes from the given text
prompt1 = PromptTemplate(
    template="Generate short and simple notes from the following text:\n{text}",
    input_variables=['text']
)


# Prompt 2:
# Generate 5 questions and their answers from the same text
prompt2 = PromptTemplate(
    template="Generate 5 questions with their answers from the following text:\n{text}",
    input_variables=['text']
)


# Prompt 3:
# Combine the notes and Q&A generated by the parallel chains
# into one clean and organized study material
prompt3 = PromptTemplate(
    template="""
Create one clean and well-organized set of study notes from the following:

NOTES:
{notes}

QUESTIONS AND ANSWERS:
{qa}

Instructions:
- Combine both inputs into a single set of notes.
- Remove duplicate information.
- Do not repeat the same fact multiple times.
- Keep all important information.
- Organize the content using clear headings and bullet points.
- Include important questions and their answers at the end.
- Do not add information that is not present in the provided text.
""",
    input_variables=['notes', 'qa']
)


# Converts the LLM's AIMessage output into a plain string
parser = StrOutputParser()


# RunnableParallel runs both chains simultaneously
# using the same input text.
#
# notes → prompt1 → model1 → parser
# qa    → prompt2 → model2 → parser
parallel_chain = RunnableParallel({
    "notes": prompt1 | model1 | parser,
    "qa": prompt2 | model2 | parser
})


# Chain responsible for merging the notes and Q&A
# generated by the parallel chain
merge_chain = prompt3 | model1 | parser


# Complete LCEL chain:
#
# Input
#   ↓
# RunnableParallel
#   ├── Generate Notes
#   └── Generate Q&A
#   ↓
# Merge both outputs
#   ↓
# Final Output
chain = parallel_chain | merge_chain


# Original text that will be passed to both parallel chains
text = """
Support vector machines (SVMs) are a set of supervised learning methods used for classification, regression and outliers detection.
The advantages of support vector machines are:
Effective in high dimensional spaces.
Still effective in cases where number of dimensions is greater than the number of samples.
Uses a subset of training points in the decision function (called support vectors), so it is also memory efficient.
Versatile: different Kernel functions can be specified for the decision function. Common kernels are provided, but it is also possible to specify custom kernels.
The disadvantages of support vector machines include:
If the number of features is much greater than the number of samples, avoid over-fitting in choosing Kernel functions and regularization term is crucial.
SVMs do not directly provide probability estimates, these are calculated using an expensive five-fold cross-validation (see Scores and probabilities, below).
The support vector machines in scikit-learn support both dense (numpy.ndarray and convertible to that by numpy.asarray) and sparse (any scipy.sparse) sample vectors as input. However, to use an SVM to make predictions for sparse data, it must have been fit on such data. For optimal performance, use C-ordered numpy.ndarray (dense) or scipy.sparse.csr_matrix (sparse) with dtype=float64.
"""


# Invoke the complete chain by providing the input text
response = chain.invoke({
    'text': text
})


# Print the final merged study notes
print(response)