from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

load_dotenv()

# Initialize the LLM
model = ChatOpenAI()


# Prompt 1: Generate a detailed report on the given topic
template1 = PromptTemplate(
    template="Generate a detailed report on {topic}",
    input_variables=['topic']
)


# Prompt 2: Take the report generated by the first prompt
# and summarize it into 5 bullet points
template2 = PromptTemplate(
    template="Summarize the given report in 5 bullet points.\n{report}",
    input_variables=['report']
)


# Converts the LLM's AIMessage output into a plain Python string
parser = StrOutputParser()


# Sequential LCEL Chain:
# 1. template1 → creates the report prompt
# 2. model → generates the detailed report
# 3. parser → converts AIMessage to string
# 4. template2 → uses the report as input
# 5. model → generates the summary
# 6. parser → converts the final AIMessage to string
chain = template1 | model | parser | template2 | model | parser


# Pass the topic to {topic} in template1
result = chain.invoke({
    'topic': "Unemployment in India"
})


# Print the final 5-bullet summary
print(result)